<a href="https://colab.research.google.com/github/thiselvan/ml-project/blob/main/Copy_of_Lesson10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

Name,Score,Grade,Age
Ali,78,B,20
Sara,,A,22
John,85,B,
Maya,60,C,20
John,85,B,20
,92,A,23

SyntaxError: invalid syntax (1229211130.py, line 3)

1. missing values?
2. should we drop the missing values or replace them?
3. duplicate values?
4. are the data types correct?

In [ ]:
import pandas as pd


data = {
   "Name":  ["Ali", "Sara", "John", "Maya", "John", None, "Tom"],
   "Score": [78, None, 85, 60, 85, 92, None],
   "Grade": ["B", "A", "B", "C", "B", "A", "A"],
   "Age":   [20, 22, None, 20, None, 23, 21]
}


df = pd.DataFrame(data)
print(df)

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
1  Sara    NaN     A  22.0
2  John   85.0     B   NaN
3  Maya   60.0     C  20.0
4  John   85.0     B   NaN
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

In [ ]:
print(df.isnull())

In [ ]:
print((df.isnull().sum() / len(df) * 100).round(1))

Name     14.3
Score    28.6
Grade     0.0
Age      28.6
dtype: float64

In [ ]:
print(df[df.isnull().any(axis=1)])

   Name  Score Grade   Age
1  Sara    NaN     A  22.0
2  John   85.0     B   NaN
4  John   85.0     B   NaN
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

In [ ]:
# Drop any row with at least one null
df_dropped = df.dropna()
print(df_dropped)
print(len(df_dropped))

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
3  Maya   60.0     C  20.0
2

In [ ]:
df_dropped

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
3  Maya   60.0     C  20.0

In [ ]:
df

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
1  Sara    NaN     A  22.0
2  John   85.0     B   NaN
3  Maya   60.0     C  20.0
4  John   85.0     B   NaN
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

In [ ]:
# Only drop rows where Score is missing
df_score_clean = df.dropna(subset=["Score"])
print(df_score_clean)

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
2  John   85.0     B   NaN
3  Maya   60.0     C  20.0
4  John   85.0     B   NaN
5  None   92.0     A  23.0

In [ ]:
df.dropna()          # ❌ df is unchanged — result is lost
df_new = df.dropna()     # ✅ df is updated

In [ ]:
# Drop an entire column
df_no_age = df.drop(columns=["Age"])
print(df_no_age)

   Name  Score Grade
0   Ali   78.0     B
1  Sara    NaN     A
2  John   85.0     B
3  Maya   60.0     C
4  John   85.0     B
5  None   92.0     A
6   Tom    NaN     A

1. fixed value
2. mean or median
3. replace with above or below

In [ ]:
# Fill missing Name with "Unknown"
df_filled = df.copy()   # always work on a copy
df_filled["Name"] = df_filled["Name"].fillna("Unknown")
print(df_filled[["Name", "Score"]])

             Name  Score
0             Ali   78.0
1            Sara    NaN
2            John   85.0
3            Maya   60.0
4            John   85.0
5  Name not found   92.0
6             Tom    NaN

In [ ]:
# Fill Score with the mean
score_mean = df_filled["Score"].mean()
print(score_mean)
df_filled["Score"] = df_filled["Score"].fillna(score_mean)
print(df_filled[["Name", "Score"]])

80.0
             Name  Score
0             Ali   78.0
1            Sara   80.0
2            John   85.0
3            Maya   60.0
4            John   85.0
5  Name not found   92.0
6             Tom   80.0

In [ ]:
# Fill Age with median
age_median = df_filled["Age"].median()
df_filled["Age"] = df_filled["Age"].fillna(age_median)
print(df_filled)

             Name  Score Grade   Age
0             Ali   78.0     B  20.0
1            Sara   80.0     A  22.0
2            John   85.0     B  21.0
3            Maya   60.0     C  20.0
4            John   85.0     B  21.0
5  Name not found   92.0     A  23.0
6             Tom   80.0     A  21.0

In [ ]:
print(df_filled.isnull().sum())

Name     0
Score    0
Grade    0
Age      0
dtype: int64

In [ ]:
print(df)

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
1  Sara    NaN     A  22.0
2  John   85.0     B   NaN
3  Maya   60.0     C  20.0
4  John   85.0     B   NaN
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

In [ ]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [ ]:
print(df.duplicated().sum())

1

In [ ]:
print(df[df.duplicated()])

   Name  Score Grade  Age
4  John   85.0     B  NaN

In [ ]:
df_no_dupes = df.drop_duplicates()
print(len(df))
print(len(df_no_dupes))
print(df_no_dupes)

7
6
   Name  Score Grade   Age
0   Ali   78.0     B  20.0
1  Sara    NaN     A  22.0
2  John   85.0     B   NaN
3  Maya   60.0     C  20.0
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

In [ ]:
df.drop_duplicates(keep="last")

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
1  Sara    NaN     A  22.0
3  Maya   60.0     C  20.0
4  John   85.0     B   NaN
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

In [ ]:
df.drop_duplicates(keep=False)

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
1  Sara    NaN     A  22.0
3  Maya   60.0     C  20.0
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

In [ ]:
print(df[df.duplicated(subset=["Grade"], keep=False)])

   Name  Score Grade   Age
0   Ali   78.0     B  20.0
1  Sara    NaN     A  22.0
2  John   85.0     B   NaN
4  John   85.0     B   NaN
5  None   92.0     A  23.0
6   Tom    NaN     A  21.0

Categorical

Numerical

In [ ]:
print(df_filled.dtypes)

Name      object
Score    float64
Grade     object
Age      float64
dtype: object

In [ ]:
df_filled["Grade"] = df_filled["Grade"].astype("category")
print(df_filled["Grade"].dtype)
print(df_filled["Grade"].cat.categories)

category
Index(['A', 'B', 'C'], dtype='object')

In [ ]:
print(df_filled["Grade"].value_counts())

Grade
A    3
B    3
C    1
Name: count, dtype: int64

In [ ]:
# Simulate a broken column loaded as text
df_filled["Score_text"] = df_filled["Score"].astype(str)
print(df_filled["Score_text"].dtype)

object

In [ ]:
print(df_filled["Score_text"].mean())

TypeError: Could not convert string '78.080.085.060.085.092.080.0' to numeric

In [ ]:
df_filled["Score_fixed"] = pd.to_numeric(df_filled["Score_text"], errors="coerce")
print(df_filled["Score_fixed"].dtype)
print(df_filled["Score_fixed"].mean())

float64
80.0

In [ ]:
pd.to_numeric(column, errors="raise")   # ❌ Crashes on bad values
pd.to_numeric(column, errors="coerce")  # ✅ Converts bad values to NaN

In [ ]:
import pandas as pd


def null_report(df):
   total_rows = len(df)
   null_counts = df.isnull().sum()
   null_pct = (null_counts / total_rows * 100).round(1)


   print("=== NULL REPORT ===")
   print(f"Total rows: {total_rows}")
   print(f"Total columns: {len(df.columns)}\n")


   for col in df.columns:
       count = null_counts[col]
       pct = null_pct[col]
       status = "✓ CLEAN" if count == 0 else f"✗ {count} missing ({pct}%)"
       print(f"  {col:<10} {status}")


# --- Run it ---
data = {
   "Name":  ["Ali", "Sara", "John", None, "Tom"],
   "Score": [78, None, 85, 92, None],
   "Grade": ["B", "A", "B", "A", "A"]
}
df = pd.DataFrame(data)
null_report(df)

=== NULL REPORT ===
Total rows: 5
Total columns: 3

  Name       ✗ 1 missing (20.0%)
  Score      ✗ 2 missing (40.0%)
  Grade      ✓ CLEAN