<a href="https://colab.research.google.com/github/thiselvan/ml-project/blob/main/Lesson12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
sales_data = {
    'waiter': ['John', 'Mary', 'John', 'Bob', 'Mary'],
    'total': [120, 120, 80, 250, 50]
}

In [ ]:
import pandas as pd

In [ ]:
sales = pd.DataFrame(sales_data)

In [ ]:
sales_data

{'waiter': ['John', 'Mary', 'John', 'Bob', 'Mary'],
 'total': [120, 150, 80, 200, 50]}

In [ ]:
sales

  waiter  total
0   John    120
1   Mary    120
2   John     80
3    Bob    250
4   Mary     50

In [ ]:
sales.groupby('waiter')['total'].sum()

waiter
Bob     250
John    200
Mary    170
Name: total, dtype: int64

In [ ]:
movie name, movie id, categoty, person name

person name , category, movie id

In [ ]:

# Sample sales data
data = {
   'product': ['Laptop', 'Mouse', 'Laptop', 'Keyboard', 'Mouse'],
   'sales': [1200, 25, 1100, 75, 30],
   'region': ['East', 'East', 'West', 'West', 'East']
}
df = pd.DataFrame(data)
print(df)

    product  sales region
0    Laptop   1200   East
1     Mouse     25   East
2    Laptop   1100   West
3  Keyboard     75   West
4     Mouse     30   East

In [ ]:
# sales per product

result = df.groupby('product')['sales'].sum()
print(result)

product
Keyboard      75
Laptop      2300
Mouse         55
Name: sales, dtype: int64

In [ ]:
# count of products per region

result = df.groupby('region')['product'].count()
print(result)

region
East    3
West    2
Name: product, dtype: int64

In [ ]:
result = df.groupby('product')['sales'].sum()
result

product
Keyboard      75
Laptop      2300
Mouse         55
Name: sales, dtype: int64

In [ ]:
result = df.groupby('product').sum()
result

          sales    region
product
Keyboard     75      West
Laptop     2300  EastWest
Mouse        55  EastEast

In [ ]:
result = df.groupby('product').agg({'sales': ['sum', 'count']})
print(result)

         sales
           sum count
product
Keyboard    75     1
Laptop    2300     2
Mouse       55     2

In [ ]:
result = df.groupby('product')['sales'].sum()
result

In [ ]:
df['product']

0      Laptop
1       Mouse
2      Laptop
3    Keyboard
4       Mouse
Name: product, dtype: object

In [ ]:
students = pd.DataFrame({
   'name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
   'subject': ['Math', 'Math', 'Math', 'Science', 'Science', 'Science'],
   'score': [95, 78, 88, 92, 85, 90]
})
print(students)

      name  subject  score
0    Alice     Math     95
1      Bob     Math     78
2  Charlie     Math     88
3    Alice  Science     92
4      Bob  Science     85
5  Charlie  Science     90

In [ ]:
total_scores = students.groupby('name')['score'].sum()
print(total_scores)

name
Alice      187
Bob        163
Charlie    178
Name: score, dtype: int64

In [ ]:
total_scores = students.groupby('name')['score'].mean()
print(total_scores)

name
Alice      93.5
Bob        81.5
Charlie    89.0
Name: score, dtype: float64

In [ ]:
exam_count = students.groupby('name')['score'].count()
print(exam_count)

name
Alice      2
Bob        2
Charlie    2
Name: score, dtype: int64

In [ ]:
Total revenue per store? - sum
Average customer age per city? - mean
How many orders per customer? - count

COUNT
SUM
MEAN

In [ ]:
summary = students.groupby('name').agg({
   'score': ['sum', 'mean', 'count']
})
print(summary)

        score
          sum  mean count
name
Alice     187  93.5     2
Bob       163  81.5     2
Charlie   178  89.0     2

In [ ]:
sales_data = pd.DataFrame({
   'region': ['East', 'East', 'West', 'West', 'East', 'West'],
   'category': ['Electronics', 'Furniture', 'Electronics', 'Furniture', 'Electronics', 'Furniture'],
   'sales': [5000, 3000, 4500, 2800, 5200, 3100]
})
print(sales_data)

  region     category  sales
0   East  Electronics   5000
1   East    Furniture   3000
2   West  Electronics   4500
3   West    Furniture   2800
4   East  Electronics   5200
5   West    Furniture   3100

In [ ]:
regional_category = sales_data.groupby(['region', 'category'])['sales'].sum()
print(regional_category)

region  category
East    Electronics    10200
        Furniture       3000
West    Electronics     4500
        Furniture       5900
Name: sales, dtype: int64

In [ ]:
regional_category = sales_data.groupby(['category', 'region'])['sales'].sum()
print(regional_category)

category     region
Electronics  East      10200
             West       4500
Furniture    East       3000
             West       5900
Name: sales, dtype: int64

In [ ]:
result = sales_data.groupby(['region', 'category'])['sales'].sum().reset_index()
print(result)

  region     category  sales
0   East  Electronics  10200
1   East    Furniture   3000
2   West  Electronics   4500
3   West    Furniture   5900

In [ ]:
pivot = sales_data.pivot_table(
   values='sales',      # What to calculate
   index='region',      # Rows
   columns='category',  # Columns
   aggfunc='sum'        # How to aggregate
)
print(pivot)

category  Electronics  Furniture
region
East            10200       3000
West             4500       5900

In [ ]:
pivot = students.pivot_table(
   values='score',
   index='name',
   columns='subject',
   aggfunc='mean'
)
print(pivot)

subject  Math  Science
name
Alice    95.0     92.0
Bob      78.0     85.0
Charlie  88.0     90.0

In [ ]:
def score_range(series):
   return series.max() - series.min()


# Apply to grouped data
result = students.groupby('name')['score'].agg(score_range)
print(result)

name
Alice      3
Bob        7
Charlie    2
Name: score, dtype: int64

In [ ]:
def score_range(x):
   return x.max() - x.min()


def above_90(x):
   return (x > 90).sum()  # Count scores above 90


result = students.groupby('name')['score'].agg(['mean', score_range, above_90])
print(result)

         mean  score_range  above_90
name
Alice    93.5            3         2
Bob      81.5            7         0
Charlie  89.0            2         0

In [ ]:
# Real-world sales data
sales = pd.DataFrame({
   'date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03'],
   'salesperson': ['John', 'Mary', 'John', 'Mary', 'John'],
   'product': ['Laptop', 'Mouse', 'Keyboard', 'Laptop', 'Monitor'],
   'amount': [1200, 25, 75, 1150, 300]
})

In [ ]:
sales

         date salesperson   product  amount
0  2024-01-01        John    Laptop    1200
1  2024-01-01        Mary     Mouse      25
2  2024-01-02        John  Keyboard      75
3  2024-01-02        Mary    Laptop    1150
4  2024-01-03        John   Monitor     300

In [ ]:
# Question 1: Who sold the most total?
top_seller = sales.groupby('salesperson')['amount'].sum().sort_values(ascending=False)
print("Top Sellers:")
print(top_seller)

Top Sellers:
salesperson
John    1575
Mary    1175
Name: amount, dtype: int64

In [ ]:
# Question 2: What's the average deal size per person?
avg_deal = sales.groupby('salesperson')['amount'].mean()
print("\nAverage Deal Size:")
print(avg_deal)

Average Deal Size:
salesperson
John    525.0
Mary    587.5
Name: amount, dtype: float64

In [ ]:
# E-commerce transactions
orders = pd.DataFrame({
   'order_id': range(1, 13),
   'category': ['Electronics', 'Clothing', 'Electronics', 'Home'] * 3,
   'region': ['North', 'North', 'South', 'South'] * 3,
   'revenue': [1200, 300, 1500, 450, 1100, 280, 1600, 500, 1300, 320, 1400, 480],
   'quantity': [2, 5, 3, 2, 2, 6, 3, 2, 2, 4, 3, 2]
})
orders

    order_id     category region  revenue  quantity
0          1  Electronics  North     1200         2
1          2     Clothing  North      300         5
2          3  Electronics  South     1500         3
3          4         Home  South      450         2
4          5  Electronics  North     1100         2
5          6     Clothing  North      280         6
6          7  Electronics  South     1600         3
7          8         Home  South      500         2
8          9  Electronics  North     1300         2
9         10     Clothing  North      320         4
10        11  Electronics  South     1400         3
11        12         Home  South      480         2

In [ ]:
# Custom function: Calculate average price per item
def avg_price_per_item(group):
   return group['revenue'].sum() / group['quantity'].sum()

In [ ]:
# Best performing category
best_category = orders.groupby('category')['revenue'].sum().idxmax()
print(f"\nTop Category: {best_category}")

Top Category: Electronics